var _AddHorizontalGiu;

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

export default (_AddHorizontalGiu = {
  "+ Add Horizontal Giude": "+ Add Horizontal Giude",
  "+ Add Vertical Giude": "+ Add Vertical Giude",
  "2D View": "2D View",
  "3D First Person": "3D First Person",
  "3D View": "3D View",
  "altitude": "altitude",
  "Altitude": "Altitude",
  "Areas": "Areas",
  "Cancel": "Cancel",
  "Catalog": "Catalog",
  "Chain selected Elements to Group": "Chain selected Elements to Group",
  "Circular": "Circular",
  "color": "color",
  "Configure layer": "Configure layer",
  "Configure project": "Configure project",
  "Confirm": "Confirm",
  "Copy": "Copy",
  "Delete group and all Elements": "Delete group and all Elements",
  "Delete layer": "Delete layer",
  "Delete": "Delete",
  "Elements on layer {0}": "Elements on layer {0}",
  "Elements": "Elements",
  "Get Screenshot": "Get Screenshot",
  "Group [{0}]": "Group [{0}]",
  "Group's Barycenter": "Group's Barycenter",
  "Group's Elements": "Group's Elements",
  "Groups": "Groups",
  "Guides": "Guides",
  "height": "height",
  "Holes": "Holes",
  "Horizontal": "Horizontal",
  "Items": "Items",
  "Last Selected": "Last Selected",
  "Layer config": "Layer config",
  "Layer": "Layer",
  "Layers": "Layers",
  "Length": "Length",
  "Lines": "Lines",
  "Load project": "Load project",
  "Mouse X Coordinate": "Mouse X Coordinate",
  "Mouse Y Coordinate": "Mouse Y Coordinate",
  "Name": "Name",
  "New Empty Group": "New Empty Group",
  "New Group from selected": "New Group from selected",
  "New layer": "New layer",
  "New project": "New project",
  "opacity": "opacity",
  "Open catalog": "Open catalog",
  "order": "order",
  "Pan": "Pan",
  "Paste": "Paste",
  "Project config": "Project config",
  "Properties: [{0}] {1}": "Properties: [{0}] {1}",
  "Prototype": "Prototype",
  "Reset": "Reset",
  "Rotation": "Rotation",
  "Save project": "Save project",
  "Save": "Save",
  "Scene Zoom Level": "Scene Zoom Level",
  "Search Element": "Search Element",
  "Snap to Grid": "Snap to Grid",
  "Snap to Guide": "Snap to Guide",
  "Snap to Line": "Snap to Line",
  "Snap to Point": "Snap to Point",
  "Snap to Segment": "Snap to Segment",
  "texture": "texture",
  "thickness": "thickness",
  "Toggle Group Visibility": "Toggle Group Visibility",
  "Un-chain all Group\'s Elements and remove Group": "Un-chain all Group\'s Elements and remove Group",
  "Un-chain Element from Group": "Un-chain Element from Group",
  "Undo (CTRL-Z)": "Undo (CTRL-Z)",
  "Unselect": "Unselect",
  "Vertical": "Vertical",
  "width": "width",
  "Would you want to start a new Project?": "Would you want to start a new Project?",
  "Zoom in": "Zoom in",
  "Zoom out": "Zoom out",
  "sash window": "sash window",
  "Sash window": "Sash window",
  "wall": "wall",
  "Wall with bricks": "Wall with bricks",
  "gate": "Gate",
  "hole in the wall": "hole in the wall",
  "air Conditioner": "Air Conditioner",
  "air conditioner": "air conditioner",
  "furnishings": "furnishings",
  "metal": "metal",
  "armchairs": "Armchairs",
  "wood": "wood",
  "balcony": "Balcony",
  "bench": "Bench"
}, _defineProperty(_AddHorizontalGiu, "bench", "Bench"), _defineProperty(_AddHorizontalGiu, "blackboard", "Blackboard"), _defineProperty(_AddHorizontalGiu, "bookcase", "Bookcase"), _defineProperty(_AddHorizontalGiu, "camera", "Camera"), _defineProperty(_AddHorizontalGiu, "canteen table", "Canteen Table"), _defineProperty(_AddHorizontalGiu, "canteen cart", "Canteen Cart"), _defineProperty(_AddHorizontalGiu, "chair", "Chair"), _defineProperty(_AddHorizontalGiu, "office chair", "Office chair"), _defineProperty(_AddHorizontalGiu, "child chair desk", "Child Chair Desk"), _defineProperty(_AddHorizontalGiu, "cleaning cart", "Cleaning Cart"), _defineProperty(_AddHorizontalGiu, "plastic", "plastic"), _defineProperty(_AddHorizontalGiu, "coat hook", "Coat Hook"), _defineProperty(_AddHorizontalGiu, "option", "option"), _defineProperty(_AddHorizontalGiu, "square dolumn", "Square Column"), _defineProperty(_AddHorizontalGiu, "round column", "Round Column"), _defineProperty(_AddHorizontalGiu, "cube", "Cube"), _defineProperty(_AddHorizontalGiu, "school desk", "School Desk"), _defineProperty(_AddHorizontalGiu, "double school desk", "Double School Desk"), _defineProperty(_AddHorizontalGiu, "desk", "Desk"), _defineProperty(_AddHorizontalGiu, "electric panel", "Electric Panel"), _defineProperty(_AddHorizontalGiu, "fire extinguisher", "Fire Extinguisher"), _defineProperty(_AddHorizontalGiu, "fridge", "Fridge"), _defineProperty(_AddHorizontalGiu, "hanger", "Hanger"), _defineProperty(_AddHorizontalGiu, "hiroos", "Hiroos "), _defineProperty(_AddHorizontalGiu, "hub", "Hub"), _defineProperty(_AddHorizontalGiu, "kitchen", "Kitchen"), _defineProperty(_AddHorizontalGiu, "multimedia chalkboard", "Multimedia Chalkboard"), _defineProperty(_AddHorizontalGiu, "metal detector", "Metal Detector"), _defineProperty(_AddHorizontalGiu, "Pc", "Pc"), _defineProperty(_AddHorizontalGiu, "maspo", "Naspo"), _defineProperty(_AddHorizontalGiu, "projector", "Projector"), _defineProperty(_AddHorizontalGiu, "aluminum radiator", "Aluminum Radiator"), _defineProperty(_AddHorizontalGiu, "vast Iron Radiator", "Cast Iron Radiator"), _defineProperty(_AddHorizontalGiu, "recycling Bins", "Recycling Bins"), _defineProperty(_AddHorizontalGiu, "router Wifi", "Router Wifi"), _defineProperty(_AddHorizontalGiu, "schneider", "Schneider"), _defineProperty(_AddHorizontalGiu, "school desk double", "School Desk Double"), _defineProperty(_AddHorizontalGiu, "school Desk", "School Desk"), _defineProperty(_AddHorizontalGiu, "sink", "Sink"), _defineProperty(_AddHorizontalGiu, "smoke Detector", "Smoke Detector"), _defineProperty(_AddHorizontalGiu, "sofa", "Sofa"), _defineProperty(_AddHorizontalGiu, "table", "Table"), _defineProperty(_AddHorizontalGiu, "teaching post", "Teaching Post"), _defineProperty(_AddHorizontalGiu, "three-phase panel", "Three-Phase Panel"), _defineProperty(_AddHorizontalGiu, "trash", "Trash"), _defineProperty(_AddHorizontalGiu, "tv", "Tv"), _defineProperty(_AddHorizontalGiu, "umbrella stand", "Umbrella Stand"), _defineProperty(_AddHorizontalGiu, "wardrobe", "Wardrobe"), _defineProperty(_AddHorizontalGiu, "electronics", "electronics"), _defineProperty(_AddHorizontalGiu, "door", "Door"), _defineProperty(_AddHorizontalGiu, "double door", "Double Door"), _defineProperty(_AddHorizontalGiu, "panic door", "Panic Door"), _defineProperty(_AddHorizontalGiu, "double panic door", "Double Panic Door"), _defineProperty(_AddHorizontalGiu, "sliding door", "Sliding Door"), _defineProperty(_AddHorizontalGiu, "window", "Window"), _defineProperty(_AddHorizontalGiu, "venetian blind window", "Venetian Blind Window"), _defineProperty(_AddHorizontalGiu, "curtain window", "Curtain Window"), _defineProperty(_AddHorizontalGiu, "Windows", "Windows"), _defineProperty(_AddHorizontalGiu, "Doors", "Doors"), _AddHorizontalGiu);