export default {
  "+ Add Horizontal Giude":"+ Add Horizontal Giude",
  "+ Add Vertical Giude":"+ Add Vertical Giude",
  "2D View": "2D View",
  "3D First Person": "3D First Person",
  "3D View": "3D View",
  "altitude": "altitude",
  "Altitude": "Altitude",
  "Areas":"Areas",
  "Cancel": "Cancel",
  "Catalog" : "Catalog",
  "Chain selected Elements to Group":"Chain selected Elements to Group",
  "Circular":"Circular",
  "color":"color",
  "Configure layer": "Configure layer",
  "Configure project": "Configure project",
  "Confirm": "Confirm",
  "Copy":"Copy",
  "Delete group and all Elements":"Delete group and all Elements",
  "Delete layer": "Delete layer",
  "Delete": "Delete",
  "Elements on layer {0}": "Elements on layer {0}",
  "Elements":"Elements",
  "Get Screenshot" : "Get Screenshot",
  "Group [{0}]":"Group [{0}]",
  "Group's Barycenter":"Group's Barycenter",
  "Group's Elements":"Group's Elements",
  "Groups":"Groups",
  "Guides":"Guides",
  "height": "height",
  "Holes":"Holes",
  "Horizontal":"Horizontal",
  "Items":"Items",
  "Last Selected":"Last Selected",
  "Layer config": "Layer config",
  "Layer":"Layer",
  "Layers": "Layers",
  "Length":"Length",
  "Lines":"Lines",
  "Load project": "Load project",
  "Mouse X Coordinate":"Mouse X Coordinate",
  "Mouse Y Coordinate":"Mouse Y Coordinate",
  "Name": "Name",
  "New Empty Group":"New Empty Group",
  "New Group from selected":"New Group from selected",
  "New layer": "New layer",
  "New project": "New project",
  "opacity": "opacity",
  "Open catalog": "Open catalog",
  "order": "order",
  "Pan": "Pan",
  "Paste":"Paste",
  "Project config": "Project config",
  "Properties: [{0}] {1}": "Properties: [{0}] {1}",
  "Prototype":"Prototype",
  "Reset": "Reset",
  "Rotation" : "Rotation",
  "Save project": "Save project",
  "Save": "Save",
  "Scene Zoom Level":"Scene Zoom Level",
  "Search Element":"Search Element",
  "Snap to Grid":"Snap to Grid",
  "Snap to Guide":"Snap to Guide",
  "Snap to Line":"Snap to Line",
  "Snap to Point":"Snap to Point",
  "Snap to Segment":"Snap to Segment",
  "texture":"texture",
  "thickness":"thickness",
  "Toggle Group Visibility":"Toggle Group Visibility",
  "Un-chain all Group\'s Elements and remove Group":"Un-chain all Group\'s Elements and remove Group",
  "Un-chain Element from Group":"Un-chain Element from Group",
  "Undo (CTRL-Z)": "Undo (CTRL-Z)",
  "Unselect": "Unselect",
  "Vertical":"Vertical",
  "width": "width",
  "Would you want to start a new Project?": "Would you want to start a new Project?",
  "Zoom in": "Zoom in",
  "Zoom out": "Zoom out",
  "sash window":"sash window",
  "Sash window": "Sash window",
  "wall": "wall",
  "Wall with bricks": "Wall with bricks",
  "gate": "Gate",
  "hole in the wall": "hole in the wall",
  "air Conditioner": "Air Conditioner",
  "air conditioner": "air conditioner",
  "furnishings": "furnishings",
  "metal": "metal",
  "armchairs": "Armchairs",
  "wood": "wood",
  "balcony": "Balcony",
  "bench": "Bench",
  "bench": "Bench",
  "blackboard": "Blackboard",
  "bookcase": "Bookcase",
  "camera": "Camera",
  "canteen table": "Canteen Table",
  "canteen cart": "Canteen Cart",
  "chair": "Chair",
  "office chair": "Office chair",
  "child chair desk": "Child Chair Desk",
  "cleaning cart": "Cleaning Cart",
  "plastic": "plastic",
  "coat hook": "Coat Hook",
  "option": "option",
  "square dolumn": "Square Column",
  "round column": "Round Column",
  "cube": "Cube",
  "school desk": "School Desk",
  "double school desk": "Double School Desk",
  "desk": "Desk",
  "electric panel": "Electric Panel",
  "fire extinguisher": "Fire Extinguisher",
  "fridge": "Fridge",
  "hanger": "Hanger",
  "hiroos": "Hiroos ",
  "hub": "Hub",
  "kitchen": "Kitchen",
  "multimedia chalkboard": "Multimedia Chalkboard",
  "metal detector": "Metal Detector",
  "Pc": "Pc",
"maspo": "Naspo",
"projector": "Projector",
"aluminum radiator": "Aluminum Radiator",
"vast Iron Radiator": "Cast Iron Radiator",
"recycling Bins": "Recycling Bins",
"router Wifi": "Router Wifi",
"schneider": "Schneider",
"school desk double": "School Desk Double",
"school Desk": "School Desk",
"sink": "Sink",
"smoke Detector": "Smoke Detector",
"sofa": "Sofa",
"table": "Table",
"teaching post": "Teaching Post",
"three-phase panel": "Three-Phase Panel",
"trash": "Trash",
"tv": "Tv",
"umbrella stand": "Umbrella Stand",
"wardrobe": "Wardrobe",
"electronics": "electronics",
"door": "Door",
"double door": "Double Door",
"panic door": "Panic Door",
"double panic door": "Double Panic Door",
"sliding door": "Sliding Door",
"window": "Window",
"venetian blind window": "Venetian Blind Window",
"curtain window": "Curtain Window",
"Windows": "Windows",
"Doors": "Doors",
"Texture" : "Texture",
"square-frame" : "square-frame",
"L-frame" : "L-frame",
"T-frame" : "T-frame",
"U-frame" : "U-frame",
"thap-frame" : "Thap-frame",

};
