export default {
    "+ Add Horizontal Giude":"+ Thêm theo chiều ngang",
    "+ Add Vertical Giude":"+ Thêm theo chiều dọc",
    "2D View": "Góc nhìn 2D",
    "3D First Person": "3D First Person",
    "3D View": "Góc nhìn 3D",
    "altitude": "độ cao",
    "Altitude": "Độ cao",
    "Areas":"Khu vực",
    "Cancel": "Hủy",
    "Catalog" : "Mục lục",
    "Chain selected Elements to Group":"Thêm các phần tử đã chọn vào nhóm",
    "Circular":"Dạng hình tròn",
    "color":"màu",
    "Configure layer": "Cấu hình lớp",
    "Configure project": "Cấu hình dự án",
    "Confirm": "Xác nhận",
    "Copy":"Sao chép",
    "Delete group and all Elements":"Xóa nhóm và các phần tử",
    "Delete layer": "Xóa lớp",
    "Delete": "Xóa",
    "Elements on layer {0}": "Các phần tử trên lớp {0}",
    "Elements":"Các phần tử",
    "Get Screenshot" : "Chụp màn hình",
    "Group [{0}]":"Nhóm [{0}]",
    "Group's Barycenter":"Group's Barycenter",
    "Group's Elements":"Các yếu tó của nhóm",
    "Groups":"Nhóm",
    "Guides":"Hướng dẫn",
    "height": "chiều cao",
    "Holes":"Holes",
    "Horizontal":"Chiều ngang",
    "Items":"Items",
    "Last Selected":"Được chọn lần cuối",
    "Layer config": "Cấu hình lớp",
    "Layer":"Lớp",
    "Layers": "Layers",
    "Length":"Chiều dài",
    "Lines":"Lines",
    "Load project": "Tải dự án",
    "Mouse X Coordinate":"Tọa độ X",
    "Mouse Y Coordinate":"Tọa độ Y",
    "Name": "Tên",
    "New Empty Group":"Tạo nhóm trống mới",
    "New Group from selected":"Tạo nhóm mới",
    "New layer": "Tạo lớp mới",
    "New project": "Tạo dự án mới",
    "opacity": "độ mờ",
    "Open catalog": "Mở danh mục",
    "order": "đặt hàng",
    "Pan": "Pan",
    "Paste":"Dán",
    "Project config": "Cấu hình dự án",
    "Properties: [{0}] {1}": "Đặc tính: [{0}] {1}",
    "Prototype":"Nguyên mẫu",
    "Reset": "Đặt lại",
    "Rotation" : "Xoay",
    "Save project": "Lưu dự án",
    "Save": "Lưu",
    "Scene Zoom Level":"Mức thu phóng",
    "Search Element":"Tìm kiếm",
    "Snap to Grid":"Snap to Grid",
    "Snap to Guide":"Snap to Guide",
    "Snap to Line":"Snap to Line",
    "Snap to Point":"Snap to Point",
    "Snap to Segment":"Snap to Segment",
    "texture":"kết cấu",
    "thickness":"độ dày",
    "Toggle Group Visibility":"Chuyển đổi chế độ hiển thị nhóm",
    "Un-chain all Group\'s Elements and remove Group":"Xóa phần tử khỏi nhóm và xóa nhóm",
    "Un-chain Element from Group":"Xóa phần tử khỏi nhóm",
    "Undo (CTRL-Z)": "Quay lại (CTRL-Z)",
    "Unselect": "Bỏ chọn",
    "Vertical":"Chiều dọc",
    "width": "độ dài",
    "Would you want to start a new Project?": "Bạn có muốn tạo một dự án mới không?",
    "Zoom in": "Phóng to",
    "Zoom out": "Thu nhỏ",
    "sash window":"cửa sổ trượt",
  "Sash window": "Cửa sổ trượt",
    "wall": "Tường",
      "Wall with bricks": "Tường xây gạch",
  "gate": "Cổng",
  "hole in the wall": "hole in the wall",
  "air Conditioner": "Máy lạnh",
  "air conditioner": "máy lạnh",
  "furnishings": "nội thất",
  "metal": "kim loại",
  "armchairs": "Ghế bành",
  "wood": "gỗ",
  "balcony": "Ban công",
  "bench": "Băng ghế",
  "blackboard": "Bảng đen",
  "bookcase": "Tủ sách",
  "camera": "Camera",
  "canteen table": "Bàn ăn",
  "canteen cart": "Xe căng tin",
  "chair": "Ghế",
  "office chair": "Ghế văn phòng",
  "child chair desk": "Bàn ghế trẻ em",
  "cleaning cart": "Xe dọn dẹp",
  "plastic": "nhựa",
  "coat hook": "Móc quần áo",
  "optiona": "optiona",
  "square column": "Cột vuông",
  "round column": "Cột tròn",
  "cube": "Khối",
  "school desk": "Bàn Học",
  "double school desk": "Bàn học đôi",
  "desk": "Bàn làm việc",
  "electric panel": "Bảng điều khiển điện",
  "fire extinguisher": "Bình cứu hỏa",
  "fridge": "Tủ lạnh",
  "hanger": "Móc áo",
  "hiroos": "Hiroos ",
  "hub": "Hub",
  "kitchen": "Bếp",
  "multimedia Chalkboard": "Bảng đen đa phương tiện",
  "metal Detector": "Máy dò kim loại",
  "pc": "Pc",
"naspo": "Naspo",
"projector": "Máy chiếu",
"aluminum radiator": "Bộ tản nhiệt nhôm",
"cast iron radiator": "Bộ tản nhiệt bằng gang",
"recycling bins": "Thùng tái chế",
"router wifi": "Thiết bị wifi",
"schneider": "Schneider",
"school desk double": "Bàn Học Đôi",
"school desk": "Bàn Học",
"sink": "Bồn rửa",
"smoke detector": "Máy báo cháy",
"sofa": "Sofa",
"table": "Bàn",
"teaching post": "Bàn giáo viên",
"three-phase panel": "Bảng điều khiển ba pha",
"trash": "Thùng rác",
"tv": "Tv",
"umbrella stand": "Giá cắm ô",
"wardrobe": "Tủ quần áo",
"electronics": "thiết bị điện tử",
"door": "Cửa",
"double door": "Cửa Đôi",
"panic door": "Cửa Thoát Hiểm",
"double panic door": "Cửa Thoát Hiểm Đôi",
"sliding door": "Cửa Trượt",
"window": "Cửa Sổ",
"venetian blind window": "Cửa Sổ Có Lưới Che",
"curtain window": "Cửa sổ Có Rèm Che",
"Windows": "Các Loại Cửa Sổ",
"Doors": "Các loại cửa"
  };
  